name: deploy docs

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    name: Deploy docs to webpage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy nyxx dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_SERVER_KEY }}
          ARGS: '-rltDzvO'
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
          TARGET: '${{ secrets.DEPLOY_REMOTE_TARGET }}/'
